# Generated by Django 4.1.5 on 2023-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'MOBILE'), ('TW', 'TOP WEAR'), ('BW', 'BOTTOM WEAR'), ('L', 'LADIES')], max_length=2),
        ),
    ]
