# Generated by Django 4.1.5 on 2023-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'MOBILE'), ('TW', 'TOP WEAR'), ('BW', 'BOTTOM WEAR'), ('L', 'LADIESTOP'), ('LB', 'LADIESBOTTOM')], max_length=2),
        ),
    ]
